CIV-9364 Fixing Camunda changes for Demages multiclaims
hmcts/civil-camunda-bpmn-definition pull request #660
Opened 2023-07-11 19:56 UTC by indu2019

Change Camunda flow diagram for Multi track claims

Context 
During the Analysis of [CIV-8602](https://tools.hmcts.net/jira/browse/CIV-8602), it was discovered that the Camunda flow diagram for Multi-track claims has changed.

Prior to SDO, multi track claims were NOT moved to Judicial Referral and were going to Notify RPA on case handed offline.

After SDO, multi track claims are now moving to Judicial Referral and are going to Notify RPA on Continuous feed.

We believe that because multi track claims are now moving to Notify RPA on Continuous feed, this is causing them not to be picked up by the batch report.

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-9364

### Change description ###
https://tools.hmcts.net/jira/browse/CIV-9364

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-07-12 11:04 UTC, asthamalviya approved these changes

2023-07-12 22:09 UTC, HarryH96 requested changes
This requirement was missed as tests were passing, should Unit tests not be updated/added to include this path so it can be caught in future?

2023-07-17 11:03 UTC, HarryH96 commented on src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseTest.java
> +    void shouldSuccessfullyCompleteClaimantResponsewithDQAndMultiClaimAndProcessGA_WhenApplicantConfirmsToProceed() {
@Test ?

2023-07-17 11:12 UTC, HarryH96 approved these changes

2023-07-17 11:48 UTC, sabahirfan approved these changes

2023-07-26 10:00 UTC, merged