CIV-7301 Add Lip flag hearing fee unpaid
hmcts/civil-camunda-bpmn-definition pull request #674
Opened 2023-07-25 11:09 UTC by miguelMolina3691

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-07-26 10:34 UTC, kurt-uk requested changes
We dont need to create new gateway, we can extend the current one to cater for Lip, also you have the yes and no the wrong way around

2023-07-27 11:08 UTC, miguelMolina3691 commented
> We dont need to create new gateway, we can extend the current one to cater for Lip, also you have the yes and no the wrong way around

2023-07-27 13:53 UTC, LeonardoPalmeiro approved these changes

2023-07-28 11:05 UTC, bhagyashreesharma90 approved these changes

2023-08-22 07:54 UTC, hmcts-version1-ignacio approved these changes

2023-08-22 08:29 UTC, LeonardoPalmeiro approved these changes

2023-08-22 08:36 UTC, merged