CIV-9123 - Added option for unrepresented defendant to trial ready schema
hmcts/civil-camunda-bpmn-definition pull request #676
Opened 2023-07-28 10:31 UTC by m-meulendijks-v1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-9123

### Change description ###

Change the Two Respondent Representatives 'No' track to:
${(!empty flowFlags.UNREPRESENTED_DEFENDANT_ONE && flowFlags.UNREPRESENTED_DEFENDANT_ONE) || (!empty flowFlags.ONE_RESPONDENT_REPRESENTATIVE && flowFlags.ONE_RESPONDENT_REPRESENTATIVE)}

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-28 10:41 UTC, LeonardoPalmeiro approved these changes

2023-07-28 10:48 UTC, bhagyashreesharma90 approved these changes

2023-07-28 15:48 UTC, kurt-uk requested changes
we also should pop in the unrepresentedrespondent2 to cover that basis too

2023-07-31 09:56 UTC, kurt-uk approved these changes

2023-08-15 11:41 UTC, merged