CIV-9040 Redetermination - Interlocutory Judgement PDF (docmosis)
hmcts/civil-camunda-bpmn-definition pull request #796
Opened 2023-11-30 17:20 UTC by manish14836

**Before creating a pull request make sure that:**

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-9040

### Change description ###

![image](https://github.com/hmcts/civil-camunda-bpmn-definition/assets/16710064/f05ab64c-a236-429f-aaee-0239725ecbb7)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-12-06 10:01 UTC, jarekPierchala requested changes

2023-12-06 10:01 UTC, jarekPierchala commented on src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
> +
no need for space here

2023-12-06 10:28 UTC, manish14836 commented on src/test/java/uk/gov/hmcts/reform/civil/bpmn/ClaimantResponseCuiTest.java
> +
Removed extra space as suggested.

2023-12-06 10:57 UTC, jarekPierchala approved these changes

2023-12-07 13:38 UTC, kenneth-hmcts approved these changes

2023-12-19 13:12 UTC, HarryH96 commented
Closing PR as ticket is PO Blocked

2024-01-17 16:32 UTC, merged